name: LiarKing

on:
  pull_request:
    branches: [release]

env:
  back_repo: ./back-end
  front_repo: ./front-end

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install back dependencies
        working-directory: ${{ env.back_repo }}
        run: npm i

      - name: Install MySQL
        run: |
          mysql --version
          sudo apt-get install -y mysql-client
          sudo service mysql start
          mysql -uroot -proot -e "CREATE DATABASE test"

      - name: Unit Test
        working-directory: ${{ env.back_repo }}
        run: npm run test
        env:
          COOKIE_SECRET: test
          TYPEORM_HOST: localhost
          TYPEORM_PORT: 3306
          TYPEORM_USERNAME: root
          TYPEORM_PASSWORD: root
          TYPEORM_DATABASE: test
          EXPRESS_PORT: ${{ secrets.EXPRESS_PORT }}

      - name: Install front dependencies
        working-directory: ${{ env.front_repo }}
        run: npm i

      - name: Build Test
        working-directory: ${{ env.front_repo }}
        run: CI= npm run build
