name: LiarKing

on:
  pull_request:
    branches: [dev]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd back-end
          npm i

      - name: Create .env
          run: |
            touch.env
            echo COOKIE_SECRET=${{ secrets.COOKIE_SECRET }}\ >> .env
            echo TYPEORM_HOST=${{ secrets.TYPEORM_HOST }}\ >> .env
            echo TYPEORM_PORT=${{ secrets.TYPEORM_PORT }}\ >> .env
            echo TYPEORM_USERNAME=${{ secrets.TYPEORM_USERNAME }}\ >> .env
            echo TYPEORM_PASSWORD=${{ secrets.TYPEORM_PASSWORD }}\ >> .env
            echo TYPEORM_DATABASE=${{ secrets.TYPEORM_DATABASE }}\ >> .env
            echo EXPRESS_PORT=${{ secrets.EXPRESS_PORT }}\ >> .env
        
      - name: Unit Test
        run: npm run test

      - name: Install dependencies
        run: |
          cd ../front-end
          npm i

      - name: Build Test
        run: CI= npm run build
      

