name: LiarKing

on:
  pull_request:
    branches: [release]

env:
  back_repo: ./back-end
  front_repo: ./front-end

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install back dependencies
        working-directory: ${{ env.back_repo }}
        run: npm i

      - name: Create .env
        working-directory: ${{ env.back_repo }}
        run: |
          touch .env
          echo COOKIE_SECRET=${{ secrets.COOKIE_SECRET }}\ >> .env
          echo TYPEORM_HOST=${{ secrets.TYPEORM_HOST }}\ >> .env
          echo TYPEORM_PORT=${{ secrets.TYPEORM_PORT }}\ >> .env
          echo TYPEORM_USERNAME=${{ secrets.TYPEORM_USERNAME }}\ >> .env
          echo TYPEORM_PASSWORD=${{ secrets.TYPEORM_PASSWORD }}\ >> .env
          echo TYPEORM_DATABASE=${{ secrets.TYPEORM_DATABASE }}\ >> .env
          echo EXPRESS_PORT=${{ secrets.EXPRESS_PORT }}\ >> .env

      - name: Unit Test
        working-directory: ${{ env.back_repo }}
        run: npm run test

      - name: Install front dependencies
        working-directory: ${{ env.front_repo }}
        run: npm i

      - name: Build Test
        working-directory: ${{ env.front_repo }}
        run: CI= npm run build
