name: LiarKing-Front

on:
  pull_request:
    branches: [dev]

env:
  front_repo: ./front-end

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ${{ env.front_repo }}
        run: npm i

      - name: Build Test
        working-directory: ${{ env.front_repo }}
        run: CI= npm run build
